spring:
  application:
    name: trip
  data:
    mongodb:
      uri: ${MONGO_TRIP_URI}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8083