version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: ridewave-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-multi-db.sql:/docker-entrypoint-initdb.d/init-multi-db.sql:ro

  mongodb:
    image: mongo:8
    container_name: ridewave-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongodata:/data/db

  rabbitmq:
    image: rabbitmq:4.0
    container_name: ridewave-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
  mongodata: